spring:
  application:
    name: MS-PRODUITS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/produits-db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: user123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6380

server:
  port: 8081
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # AJOUTÉ
  endpoint:
    health:
      show-details: always  # AJOUTÉ